version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-embedding
    ipc: host
    env_file:
      - ../.env
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/vllm/llm/models:/models
    ports:
      - "50002:8000"
    command: --model multilingual-e5-large-instruct-q8_0.gguf --trust-remote-code --tensor-parallel-size 2
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
