version: "3.9"

# ----------------------------------------------------------------------------
# docker-compose 設定：啟動 GPU 版 RAG 容器
# ----------------------------------------------------------------------------
# 使用方式：
# 1. 於 RAG 目錄執行  docker compose up  --build
# 2. 透過 -v 掛載外部模型目錄 (預設為 ./models)，可共用 Hugging Face/Torch 快取
#    若已存在其他路徑，可自行修改左側路徑即可。
# ----------------------------------------------------------------------------

services:
  rag:
    container_name: rag-gpu
    build: .          # 讀取同目錄 Dockerfile
    image: rag-gpu:latest

    # 啟用 GPU (需安裝 NVIDIA Container Toolkit)
    runtime: nvidia
    env_file:
      - ../.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # 統一模型緩存路徑配置
      - HF_HOME=/models/cache
      - TRANSFORMERS_CACHE=/models/cache
      - TORCH_HOME=/models/cache

    ports:
      - "8000:8000"
    volumes:
      # 統一模型目錄 (包含 embedding, llm, cache 子目錄)
      - ./models:/models
      # ChromaDB 持久化資料夾
      - ./chroma_db:/app/chroma_db

    command: ["python", "start_web.py"]
    restart: unless-stopped
