
version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-starcode-15B
    ipc: host
    env_file:
      - ../.env
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/vllm/llm/models:/models
      - ~/vllm/llm/models-template:/models-template
    ports:
      - "80:8000"
    #command: --model bigcode/starcoder2-15b --trust-remote-code --tensor-parallel-size 2
    #command: --model /models/starcoder2-15b-Q8_0.gguf --trust-remote-code --tensor-parallel-size 2
    command: --model /models/starcoder2-7b-Q8_0.gguf --trust-remote-code --tensor-parallel-size 2 
    #command: --model /models/starcoder2-3b-Q8_0.gguf --trust-remote-code --tensor-parallel-size 2 
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


