
version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-starcode-15B
    ipc: host
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/vllm/llm/models:/models
    ports:
      - "80:8000"
    command: --model bigcode/starcoder2-15b --trust-remote-code --tensor-parallel-size 2 --gpu-memory-utilization 0.9
#    command: --model /models/Mistral-Small-3.2-24B-Instruct-2506-Q8_0.gguf --trust-remote-code --tensor-parallel-size 2 --gpu-memory-utilization 0.95
        #    command: --model nvidia/Llama-3.1-Nemotron-Nano-8B-v1 --trust-remote-code --tensor-parallel-size 2 --gpu-memory-utilization 0.95
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


