
version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-nvidia-49B
    ipc: host
    env_file:
      - ../.env
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/vllm/llm/models:/models
    ports:
      - "80:8000"
    command: --model Ithanil/Llama-3_3-Nemotron-Super-49B-v1-FP8-Dynamic --trust-remote-code --tensor-parallel-size 2 --gpu-memory-utilization 0.9
#    command: --model /models/Mistral-Small-3.2-24B-Instruct-2506-Q8_0.gguf --trust-remote-code --tensor-parallel-size 2 --gpu-memory-utilization 0.95
        #    command: --model nvidia/Llama-3.1-Nemotron-Nano-8B-v1 --trust-remote-code --tensor-parallel-size 2 --gpu-memory-utilization 0.95
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


